name: Build and Deploy ERP UI

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install DevOps Tools
      uses: Bengo-Hub/devops-k8s/.github/actions/install-devops-tools@main

    - name: Set deployment variables
      run: |
        echo "DEPLOY=true" >> $GITHUB_ENV
        echo "SETUP_DATABASES=false" >> $GITHUB_ENV
        echo "DB_TYPES=postgres,redis" >> $GITHUB_ENV
        echo "NAMESPACE=erp" >> $GITHUB_ENV
        echo "ENV_SECRET_NAME=erp-ui-env" >> $GITHUB_ENV
        echo "REGISTRY_SERVER=docker.io" >> $GITHUB_ENV
        echo "REGISTRY_NAMESPACE=codevertex" >> $GITHUB_ENV
        echo "VALUES_FILE_PATH=apps/erp-ui/values.yaml" >> $GITHUB_ENV
        echo "DEPLOYMENT_SUMMARY_TITLE=BengoERP UI Deployment Summary" >> $GITHUB_ENV
        echo "DEPLOYMENT_SUCCESS_MESSAGE=BengoERP UI deployment completed! The UI should be accessible via the URLs above." >> $GITHUB_ENV
        echo "APPLICATION_DISPLAY_NAME=BengoERP UI" >> $GITHUB_ENV

    - name: Run production deployment
      uses: Bengo-Hub/devops-k8s/.github/workflows/reusable-build-deploy.yml@main
      with:
        app_name: erp-ui
        registry_server: docker.io
        registry_namespace: codevertex
        deploy: true
        values_file_path: apps/erp-ui/values.yaml
        namespace: erp
        git_user: ${{ secrets.GIT_USER }}
        git_email: ${{ secrets.GIT_EMAIL }}
        devops_repo: Bengo-Hub/devops-k8s
        setup_databases: false
        provider: contabo
        contabo_api: true
        deployment_summary_title: BengoERP UI Deployment Summary
        deployment_success_message: BengoERP UI deployment completed! The UI should be accessible via the URLs above.
        application_display_name: BengoERP UI
