name: Build and Deploy ERP UI

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install DevOps Tools
      uses: Bengo-Hub/devops-k8s/.github/actions/install-devops-tools@main

    - name: Validate Kubernetes configuration
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "::group::Validating KUBE_CONFIG"
        if [ -z "$KUBE_CONFIG" ]; then
          echo "❌ KUBE_CONFIG secret not set in organization"
          echo "Please configure KUBE_CONFIG organization secret with your base64-encoded kubeconfig"
          exit 1
        fi

        # Test if it's valid base64
        if ! echo "$KUBE_CONFIG" | base64 -d >/dev/null 2>&1; then
          echo "❌ KUBE_CONFIG is not valid base64"
          exit 1
        fi

        # Test if the decoded config is valid YAML
        if ! echo "$KUBE_CONFIG" | base64 -d | head -5 | grep -q "apiVersion\|kind\|clusters\|contexts\|users"; then
          echo "❌ KUBE_CONFIG does not appear to be a valid kubeconfig file"
          exit 1
        fi

        echo "✅ KUBE_CONFIG validation passed"
        echo "::endgroup::"

    - name: Run production deployment
      env:
        DOCKER_SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        GITHUB_SHA: ${{ github.sha }}
        DEPLOY: true
        SETUP_DATABASES: ${{ env.SETUP_DATABASES }}
        NAMESPACE: ${{ env.NAMESPACE }}
        ENV_SECRET_NAME: ${{ env.ENV_SECRET_NAME }}
        REGISTRY_SERVER: ${{ env.REGISTRY_SERVER }}
        REGISTRY_NAMESPACE: ${{ env.REGISTRY_NAMESPACE }}
        VALUES_FILE_PATH: ${{ env.VALUES_FILE_PATH }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # SSH deployment variables
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PROVIDER: contabo
        CONTABO_API: true
      run: |
        chmod +x build.sh
        ./build.sh
