name: Build and Deploy ERP UI

# Prevent concurrent deployments for the same app
concurrency:
  group: deploy-${{ github.ref_name }}-erp-ui
  cancel-in-progress: true

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    uses: Bengo-Hub/devops-k8s/.github/workflows/reusable-build-deploy.yml@main
    with:
      app_name: erp-ui
      registry_server: docker.io
      registry_namespace: codevertex
      deploy: true
      values_file_path: apps/erp-ui/values.yaml
      namespace: erp
      git_user: Titus Owuor
      git_email: titusowuor30@gmail.com
      devops_repo: Bengo-Hub/devops-k8s
      setup_databases: false
      provider: contabo
      contabo_api: true
      deployment_summary_title: BengoERP UI Deployment Summary
      deployment_success_message: BengoERP UI deployment completed! The UI should be accessible via the URLs above.
      application_display_name: BengoERP UI
      # Standard file skipping for UI (no payment integrations)
      skip_files: "localhost*.pem,*.key,*.crt" #<--- Standard file skipping for UI (no payment integrations)