name: Build and Deploy ERP UI

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install DevOps Tools
      uses: Bengo-Hub/devops-k8s/.github/actions/install-devops-tools@main

    - name: Set deployment variables
      run: |
        echo "DEPLOY=true" >> $GITHUB_ENV
        echo "SETUP_DATABASES=false" >> $GITHUB_ENV
        echo "DB_TYPES=postgres,redis" >> $GITHUB_ENV
        echo "NAMESPACE=erp" >> $GITHUB_ENV
        echo "ENV_SECRET_NAME=erp-ui-env" >> $GITHUB_ENV
        echo "REGISTRY_SERVER=docker.io" >> $GITHUB_ENV
        echo "REGISTRY_NAMESPACE=codevertex" >> $GITHUB_ENV
        echo "VALUES_FILE_PATH=apps/erp-ui/values.yaml" >> $GITHUB_ENV
        echo "DEPLOYMENT_SUMMARY_TITLE=BengoERP UI Deployment Summary" >> $GITHUB_ENV
        echo "DEPLOYMENT_SUCCESS_MESSAGE=BengoERP UI deployment completed! The UI should be accessible via the URLs above." >> $GITHUB_ENV
        echo "APPLICATION_DISPLAY_NAME=BengoERP UI" >> $GITHUB_ENV
        echo "VITE_API_URL=https://erpapi.masterspace.co.ke" >> $GITHUB_ENV
        echo "VITE_WEBSOCKET_URL=wss://erpapi.masterspace.co.ke/ws/pos/" >> $GITHUB_ENV

    - name: Run production deployment
      env:
        DOCKER_SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        # Use GH token for HTTPS auth fallback in build.sh
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        GITHUB_SHA: ${{ github.sha }}
        DEPLOY: true
        SETUP_DATABASES: false
        DB_TYPES: postgres,redis
        NAMESPACE: erp
        ENV_SECRET_NAME: erp-ui-env
        REGISTRY_SERVER: docker.io
        REGISTRY_NAMESPACE: codevertex
        VALUES_FILE_PATH: apps/erp-ui/values.yaml
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        # Vite build-time environment variables for API configuration
        VITE_API_URL: https://erpapi.masterspace.co.ke
        VITE_WEBSOCKET_URL: wss://erpapi.masterspace.co.ke/ws/pos/
        # SSH deployment variables
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PROVIDER: contabo
        CONTABO_API: true
        # Contabo secrets
        CONTABO_CLIENT_ID: ${{ secrets.CONTABO_CLIENT_ID }}
        CONTABO_CLIENT_SECRET: ${{ secrets.CONTABO_CLIENT_SECRET }}
        CONTABO_API_USERNAME: ${{ secrets.CONTABO_API_USERNAME }}
        CONTABO_API_PASSWORD: ${{ secrets.CONTABO_API_PASSWORD }}
        # Deployment variables
        DEPLOYMENT_SUMMARY_TITLE: BengoERP UI Deployment Summary
        DEPLOYMENT_SUCCESS_MESSAGE: BengoERP UI deployment completed! The UI should be accessible via the URLs above.
        APPLICATION_DISPLAY_NAME: BengoERP UI
      run: |
        chmod +x build.sh
        ./build.sh
