name: Build and Deploy ERP UI

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install DevOps Tools
      uses: Bengo-Hub/devops-k8s/.github/actions/install-devops-tools@main

    - name: Set deployment variables
      run: |
        echo "DEPLOY=true" >> $GITHUB_ENV
        echo "SETUP_DATABASES=false" >> $GITHUB_ENV
        echo "NAMESPACE=erp" >> $GITHUB_ENV
        echo "ENV_SECRET_NAME=erp-ui-env" >> $GITHUB_ENV
        echo "REGISTRY_SERVER=docker.io" >> $GITHUB_ENV
        echo "REGISTRY_NAMESPACE=codevertex" >> $GITHUB_ENV
        echo "VALUES_FILE_PATH=apps/erp-ui/values.yaml" >> $GITHUB_ENV

    - name: Run production deployment
      env:
        DOCKER_SSH_KEY: ${{ secrets.DOCKER_SSH_KEY }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        GITHUB_SHA: ${{ github.sha }}
        DEPLOY: ${{ env.DEPLOY }}
        SETUP_DATABASES: ${{ env.SETUP_DATABASES }}
        NAMESPACE: ${{ env.NAMESPACE }}
        ENV_SECRET_NAME: ${{ env.ENV_SECRET_NAME }}
        REGISTRY_SERVER: ${{ env.REGISTRY_SERVER }}
        REGISTRY_NAMESPACE: ${{ env.REGISTRY_NAMESPACE }}
        VALUES_FILE_PATH: ${{ env.VALUES_FILE_PATH }}
      run: |
        chmod +x build.sh
        ./build.sh
